spring:
  ai:
    openai:
      api-key: {SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
